<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Internet Type' => 'Typ internetového připojení',
    'Internet Types' => 'Typy internetových připojení',
    '-- choose a country --' => '-- vyberte zemi --',
    '-- choose a type --' => '-- vyberte typ --',
    'Add new' => 'Přidat',
    'Address' => 'adresu',
    'Address Type' => 'Typ adresy',
    'Address Types' => 'Typy adres',
    'Addresses' => 'Adresy',
    'Are you sure you want to delete this item and his all subitems?' => 'Opravdu chcete smazat tento záznam a všechny připojené záznamy?',
    'Contact addresses' => 'Kontaktní adresy',
    'Create' => 'Vytvořit',
    'Create {modelClass}' => 'Vytvořit {modelClass}',
    'Delete' => 'Smazat',
    'Email' => 'email',
    'Email Type' => 'Typ emailu',
    'Email Types' => 'Typy emailů',
    'Emails' => 'Emaily',
    'Home' => 'Úvod',
    'People' => 'Kontakty',
    'Person' => 'osobu',
    'Person Type' => 'Typ kontaktu',
    'Person Types' => 'Typy kontaktu',
    'Phone' => 'telefon',
    'Phone Type' => 'Typ telefonu',
    'Phone Types' => 'Typy telefonů',
    'Phones' => 'Telefony',
    'Reset' => 'Resetovat',
    'Responsible People' => 'Odpovědné osoby',
    'Search' => 'Hledat',
    'Settings' => 'Nastavení',
    'State' => 'zemi',
    'States' => 'Země',
    'Subject' => 'ubytovatele',
    'Subject uncompleted' => 'Ubytovatel není kompletní',
    'Subjects' => 'Ubytovatelé',
    'Update' => 'Změnit',
    'Update {modelClass}: ' => 'Změnit {modelClass}: ',
];
