<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Phone' => 'telefon',
    '-- choose a type --' => '-- vyberte typ --',
    'Add new' => 'Přidat nový',
    'Address Types' => 'Typy adres',
    'Addresses' => 'Adresy',
    'Are you sure you want to delete this item?' => 'Opravdu chcete smazat tuto položku?',
    'Create' => 'Vytvořit',
    'Create {modelClass}' => 'Vytvořit {modelClass}',
    'Delete' => 'Smazat',
    'Email Types' => 'Typy emailů',
    'Emails' => 'Emaily',
    'People' => 'Osoby',
    'Person' => 'osobu',
    'Phone Types' => 'Typy telefonů',
    'Phones' => 'Telefony',
    'Reset' => 'Resetovat',
    'Responsible People' => 'Odpovědné osoby',
    'Search' => 'Hledat',
    'States' => 'Státy',
    'Subject' => 'ubytovatele',
    'Subjects' => 'Ubytovatelé',
    'Update' => 'Změnit',
    'Update {modelClass}: ' => 'Změnit {modelClass}: ',
];
