<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Animals' => 'Zvířata',
    'Bath' => 'Koupelna',
    'Bed Nr' => 'Počet lůžek',
    'Bikers Welcomed' => 'Cyklisté vítáni',
    'Certificate' => 'Certifikáty',
    'Checkin From' => 'Čas ubytování od',
    'Checkin To' => 'Čas ubytování do',
    'Checkout From' => 'Čas odhlášení od',
    'Checkout To' => 'Čas odhlášení do',
    'Children' => 'Děti',
    'Description' => 'Popis',
    'Douche' => 'Sprcha',
    'Facility Type ID' => 'ID typu zařízení',
    'Fee' => 'Cena',
    'Food In Price' => 'Jídlo v ceně',
    'Food In Price Note' => 'Poznámka k jídlu v ceně',
    'Food Optional' => 'Možnost jídla',
    'Food Optional Note' => 'Poznámka k možnosti jídla',
    'ID' => '',
    'Internet' => '',
    'Internet Day Fee' => 'Denní poplatek za internet',
    'Internet Type ID' => 'ID typu internetového připojení',
    'No Barriers' => 'Bezbariérové',
    'Nr' => 'Počet',
    'Parking' => 'Parkování',
    'Parking Day Fee' => 'Denní poplatek za parkování',
    'Parking Type ID' => 'ID typu parkování',
    'Partner' => '',
    'Person Type' => 'Typ kontaktu',
    'Phone' => 'Telefon',
    'Place Type ID' => 'ID typu místa',
    'Room ID' => 'ID pokoje',
    'Room Type ID' => 'ID typu pokoje',
    'Stars' => 'Počet hvězdiček',
    'Tv' => 'Televize',
    'Wc' => 'WC',
    'Weburl' => 'URL webu',
    'Acronym' => 'Zkratka',
    'Address' => 'Adresa',
    'Address Type ID' => 'Typ adresy',
    'Back Title' => 'Titul za jménem',
    'City' => 'Město/obec',
    'Company Nr' => 'IČ',
    'Country' => 'Země',
    'Created At' => 'Vytvořeno',
    'Created By' => 'Vytvořil',
    'Email Type ID' => 'Typ emailu',
    'Front Title' => 'Titul před jménem',
    'House Nr' => 'ČP',
    'Name' => 'Jméno',
    'Note' => 'Poznámka',
    'Number' => 'Číslo',
    'Person ID' => 'Osoba',
    'Phone Type ID' => 'Typ telefonu',
    'Postal Code' => 'PSČ',
    'State ID' => 'Země',
    'Street' => 'Ulice',
    'Subject ID' => 'Ubytovatel',
    'Surname' => 'Příjmení',
    'Tax Nr' => 'DIČ',
    'Title' => 'Název',
    'Type' => 'Typ',
    'Updated At' => 'Změněno',
    'Updated By' => 'Změnil',
];
