<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktivní',
    'Bed Nr' => 'Počet lůžek',
    'Bed Nr.' => 'Počet lůžek',
    'Facility' => 'Zařízení',
    'Facility ID' => 'Zařízení',
    'Filename' => 'Název souboru',
    'ID' => '',
    'Main' => 'Hlavní',
    'Object Property' => 'Vlastnost objektu',
    'Object Type' => 'Typ objektu',
    'Partner' => '',
    'Photo' => 'Foto',
    'Place' => 'Umístění',
    'Room Type' => 'Typ pokoje',
    'Tax' => 'Daň',
    '-- not selected --' => '-- není zvoleno --',
    'Acronym' => 'Zkratka',
    'Address' => 'Adresa',
    'Address Type ID' => 'Typ adresy',
    'Back Title' => 'Titul za jménem',
    'Certificate' => 'Certifikáty',
    'Checkin From' => 'Čas ubytování od',
    'Checkin To' => 'Čas ubytování do',
    'Checkout From' => 'Čas odhlášení od',
    'Checkout To' => 'Čas odhlášení do',
    'City' => 'Město/obec',
    'Company Nr' => 'IČ',
    'Completed' => 'Kompletní',
    'Country' => 'Země',
    'Created At' => 'Vytvořeno',
    'Created By' => 'Vytvořil',
    'Description' => 'Popis',
    'Email Type' => 'Typ emailu',
    'Facility Type' => 'Typ zařízení',
    'Fee' => 'Cena',
    'Fees' => 'Poplatky',
    'Front Title' => 'Titul před jménem',
    'House Nr' => 'ČP',
    'Model Type' => 'Typ modelu',
    'Name' => 'Jméno',
    'Note' => 'Poznámka',
    'Nr' => 'Počet',
    'Number' => 'Číslo',
    'Object ID' => 'ID objekt',
    'Object Property ID' => 'ID vlastnosti objektu',
    'Person' => 'Kontakt',
    'Person Type' => 'Typ kontaktu',
    'Phone Type' => 'Typ telefonu',
    'Postal Code' => 'PSČ',
    'Property ID' => 'ID vlastnosti',
    'Property Note' => 'Poznámka k vlastnosti',
    'Property Type' => 'Typ vlastnosti',
    'Property Value' => 'Hodnota vlastnosti',
    'Room ID' => 'ID pokoje',
    'Stars' => 'Počet hvězdiček',
    'State' => 'Stát',
    'Street' => 'Ulice',
    'Subject' => 'Ubytovatel',
    'Subject ID' => 'Ubytovatel',
    'Surname' => 'Příjmení',
    'Tax Nr' => 'DIČ',
    'Title' => 'Název',
    'Type ID' => 'ID typu',
    'Type of Catering' => 'Typ stravování',
    'Type of Internet' => 'Typ internetu',
    'Type of Parking' => 'Typ parkování',
    'Types' => 'Typy',
    'Updated At' => 'Změněno',
    'Updated By' => 'Změnil',
    'Value' => 'Hodnota',
    'Weburl' => 'URL webu',
];
