<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced options of searching' => 'Rozšířené možnosti vyhledávání',
    'Requested attributes of accommodations facility' => 'Požadované vlastnosti ubytovacího zařízení',
    'Requested attributes of room' => 'Požadované vlastnosti pokoje',
    'Search' => 'Hledat',
    'Search for accomodation in Slavonice' => 'Hledat ubytování ve Slavonicích',
    'Number of beds' => 'Počet lůžek',
    'Place of accommodation facility' => 'Poloha ubytování',
    'Price from (person and night)' => 'Cena od (osoba a noc)',
    'Price to (person and night)' => 'Cena do (osoba a noc)',
    'Type of accommodation facility' => 'Typ ubytovacího zařízení',
    'Verification code' => 'Ověřovací kód',
];
