<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'prices' => 'ceny',
    'Advanced options of searching' => 'Rozšířené možnosti vyhledávání',
    'Booking request' => 'Požadavek na rezervaci',
    'Booking request successfully sent!' => 'Váš požadavek na rezervaci byl úspěšně odeslán!',
    'CZK' => 'Kč',
    'Certificate' => 'Certifikáty',
    'Check in from' => 'Přihlášení od',
    'Check in to' => 'Přihlášení do',
    'Check out from' => 'Odhlášení od',
    'Check out to' => 'Odhlášení do',
    'Close' => 'Zavřít',
    'Contact form' => 'Kontaktní formulář',
    'Details' => 'Detaily',
    'Details of accommodation' => 'Detaily ubytování',
    'Details of facility' => 'Detaily ubytování',
    'Fees' => 'Poplatky',
    'List of accommodation' => 'Seznam ubytování',
    'Message from ' => 'Zpráva od',
    'Number of beds' => 'Počet lůžek',
    'Our rooms' => 'Naše pokoje',
    'Place of accomodation facility' => 'Poloha ubytovacího zařízení',
    'Please contact us if you think this is a server error. Thank you.' => 'Pokud si myslíte, že je to chyba serveru, tak nás kontaktujte. Díky ;)',
    'Price from (person and night)' => 'Cena od (osoba a noc)',
    'Price to (person and night)' => 'Cena do (osoba a noc)',
    'Prices' => 'Ceny',
    'Requested attributes of accommodations facility' => 'Požadované vlastnosti ubytovacího zařízení',
    'Requested attributes of room' => 'Požadované vlastnosti pokoje',
    'Return page not found' => 'Stránka pro návrat nebyla nalezena',
    'Room' => 'Pokoj',
    'Search' => 'Hledat',
    'Search for accomodation in Slavonice' => 'Hledat ubytování ve Slavonicích',
    'Send message' => 'Poslat zprávu',
    'Send request' => 'Poslat požadavek',
    'Server operator' => 'Provozovatel serveru',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Děkujeme Vám, že jste nás kontaktovali. Odpovíme co nejdříve.',
    'The above error occurred while the Web server was processing your request.' => 'Při zpracování požadavku nastala výše uvedená chyba.',
    'There was an error sending email.' => 'Při odesílání zprávy se vyskytla chyba',
    'Total beds number' => 'Celkový počet lůžek',
    'Type of accomodation facility' => 'Typ ubytovacího zařízení',
    'Verification Code' => 'Ověřovací kód',
    'Your email' => 'Váš email',
    'Your message' => 'Vaše zpráva',
    'Your name' => 'Vaše jméno',
    'beds' => 'lůžka',
    'description' => 'popis',
    'detailed information of room' => 'detaily pokoje',
    'incl. VAT' => 's DPH',
    'list of accommodation' => 'seznam ubytování',
    'unavailable' => 'obsazeno',
];
